{"name": "Проверка счетчика количества ингредиентов, добавленных в заказ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (475, 845) is out of bounds of viewport dimensions (1280, 657)\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nMoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nassertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2338:11\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1144:21\ndispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2010:14\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2009:39\ndispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1920:27\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1922:7\nperformActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:508:23\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:143:31", "trace": "self = <tests.test_constructor.TestConstructor object at 0x00000243849432C0>\nregistered_user = {'email': 'k5mmaheodrlwon@ya.ru', 'name': 'k5mmaheodrlwon', 'password': 'ccdqepdekr'}\nrequest = <FixtureRequest for <Function test_check_ingredient_counter[firefox_driver]>>, br_driver = 'firefox_driver'\n\n    @allure.title('Проверка счетчика количества ингредиентов, добавленных в заказ')\n    @allure.description('Пользователь находится на главной странице, перетаскавает произвольный ингредиент в поле '\n                        'заказа. '\n                        'Счетчик над ингредиентом увеличивается. '\n                        'Для булок счетчик увеличивается на 2, для соусов и начинок на 1.')\n    @pytest.mark.parametrize('br_driver',\n                             ['chrome_driver', 'firefox_driver'])\n    def test_check_ingredient_counter(self, registered_user, request, br_driver):\n        driver = request.getfixturevalue(br_driver)\n        main_page = MainPage(driver)\n        constructor_page = ConstructorPage(driver)\n        main_page.open_main_page()\n    \n        ingredient = constructor_page.choose_any_ingredient_from_list()\n>       constructor_page.drag_ingredient(ingredient)\n\ntests\\test_constructor.py:58: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_object\\pages\\constructor_page.py:45: in drag_ingredient\n    action.drag_and_drop(moving_element, destination_element).perform()\nC:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py:94: in perform\n    self.w3c_actions.perform()\nC:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py:96: in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\nC:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:347: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x0000024384AB42F0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"move target out of bounds\",\"message\":\"Move target (475, 845) is out of bo...ys.mjs:508:23\\\\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:143:31\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (475, 845) is out of bounds of viewport dimensions (1280, 657)\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       MoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nE       assertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2338:11\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1144:21\nE       dispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2010:14\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2009:39\nE       dispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1920:27\nE       dispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1922:7\nE       performActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:508:23\nE       receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:143:31\n\nC:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: MoveTargetOutOfBoundsException"}, "description": "Пользователь находится на главной странице, перетаскавает произвольный ингредиент в поле заказа. Счетчик над ингредиентом увеличивается. Для булок счетчик увеличивается на 2, для соусов и начинок на 1.", "steps": [{"name": "Открыть главную страницу", "status": "passed", "steps": [{"name": "Открыть страницу кликнув на элемент", "status": "passed", "steps": [{"name": "Перейти на страницу", "status": "passed", "parameters": [{"name": "url", "value": "'https://stellarburgers.nomoreparties.site/'"}], "start": 1714918519772, "stop": 1714918521161}, {"name": "Подождать", "status": "passed", "start": 1714918521236, "stop": 1714918521236}], "parameters": [{"name": "locator", "value": "('xpath', \".//h1[contains(text(),'Соберите бургер')]\")"}, {"name": "page_url", "value": "'https://stellarburgers.nomoreparties.site/'"}, {"name": "page", "value": "<page_object.pages.main_page.MainPage object at 0x0000024384AB49E0>"}], "start": 1714918519772, "stop": 1714918521236}], "start": 1714918519771, "stop": 1714918521236}, {"name": "Выбор произвольного ингрелиента", "status": "passed", "start": 1714918521236, "stop": 1714918521243}, {"name": "Перетащить элемент", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: Move target (475, 845) is out of bounds of viewport dimensions (1280, 657)\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nMoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:479:5\nassertInViewPort@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2338:11\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1144:21\ndispatch/pendingEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2010:14\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:2009:39\ndispatch/chainEvents<@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1920:27\ndispatch@chrome://remote/content/shared/webdriver/Actions.sys.mjs:1922:7\nperformActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:508:23\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:143:31\n\n", "trace": "  File \"C:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\trainings\\yandex_praktikum_git\\Diplom_3_Natalia_Uvarova_5\\Diplom_3\\page_object\\pages\\constructor_page.py\", line 45, in drag_ingredient\n    action.drag_and_drop(moving_element, destination_element).perform()\n  File \"C:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\action_chains.py\", line 94, in perform\n    self.w3c_actions.perform()\n  File \"C:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\actions\\action_builder.py\", line 96, in perform\n    self.driver.execute(Command.W3C_ACTIONS, enc)\n  File \"C:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\natasha\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Найти элемент с ожиданием", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \".//span[@class='constructor-element__row']\")"}], "start": 1714918521243, "stop": 1714918521285}], "parameters": [{"name": "moving_element", "value": "<selenium.webdriver.remote.webelement.WebElement (session=\"a00ac5f1-5fab-44bb-bd62-a8c0ca862226\", element=\"1bb712a9-656b-4ef2-8704-d14e53c1ceec\")>"}], "start": 1714918521243, "stop": 1714918521297}], "parameters": [{"name": "br_driver", "value": "'firefox_driver'"}], "start": 1714918514003, "stop": 1714918521309, "uuid": "20680d1c-6ea7-438e-9e35-8e3b861a6ce3", "historyId": "1e3ce996efd64501126e4ef0256c8d2c", "testCaseId": "19e67f064823593c9d6b1a13c56aba61", "fullName": "tests.test_constructor.TestConstructor#test_check_ingredient_counter", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_constructor"}, {"name": "subSuite", "value": "TestConstructor"}, {"name": "host", "value": "LAPTOP-IE2IJGHD"}, {"name": "thread", "value": "8976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_constructor"}]}